---
title: "Chapter 8 Practice"
author: "Keith Williams"
date: "1/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rethinking)
ggplot2::theme_set(theme_minimal())
```

# Notes

```{r}
## R code 8.1
num_weeks <- 1e5
positions <- rep(0,num_weeks)
current <- 10
for ( i in 1:num_weeks ) {
    # record current position
    positions[i] <- current

    # flip coin to generate proposal
    proposal <- current + sample( c(-1,1) , size=1 )
    # now make sure he loops around the archipelago
    if ( proposal < 1 ) proposal <- 10
    if ( proposal > 10 ) proposal <- 1

    # move?
    prob_move <- proposal/current
    current <- ifelse( runif(1) < prob_move , proposal , current )
}

king_markov <- tibble(
  week = 1:num_weeks,
  position = positions
)

ggplot(king_markov, aes(position)) + 
  geom_bar() +
  labs(title = "counts of visit to each island is proportional to their population")

ggplot(head(king_markov, 1000), aes(week, position)) + 
  geom_line() +
  geom_point(alpha = 0.1, size = 4) +
  labs(title = "Path first 1000 weeks")

# rewrite with any island as a candidate  
islands <- 1:10
visited <- numeric(length = num_weeks)
current <- 10
for (i in 1:num_weeks) {
  visited[i] <- current
  
  proposal <- sample(islands, 1) * 1
  prob_move <- proposal / current
  current <- ifelse(runif(1) < prob_move, proposal, current)
}

brave_king_markov <- tibble(
  week = 1:num_weeks,
  position = visited
)

ggplot(brave_king_markov, aes(position)) + 
  geom_bar() +
  labs(title = "counts of visit to each island is proportional to their population")

ggplot(head(brave_king_markov, 500), aes(week, position)) + 
  geom_line(alpha = 0.7) +
  geom_point(alpha = 0.1, size = 4) +
  labs(title = "Path first 1000 weeks")
```

```{r}
data(rugged)
detach(package:rethinking, unload = TRUE)

rugged <- rugged %>% 
  mutate(log_gdp = log(rgdppc_2000))

rugged_complete <- drop_na(rugged, rgdppc_2000)

ggplot(rugged_complete, aes(rugged, log_gdp, color = as.factor(cont_africa))) + 
  geom_point()
```

```{r}
library(brms)

b8_1 <- brm(
  formula = log_gdp ~ 1 + rugged + cont_africa + rugged:cont_africa,
  data = rugged_complete,
  family = gaussian,
  prior = c(
    prior(normal(0, 100), class = Intercept),
    prior(normal(0, 10), class = b),
    prior(cauchy(0, 2), class = sigma)
  ),
  seed = 8
)

print(b8_1)
plot(b8_1)
```

```{r}
b8_1_par <- brm(
  formula = log_gdp ~ 1 + rugged + cont_africa + rugged:cont_africa,
  data = rugged_complete,
  family = gaussian,
  prior = c(
    prior(normal(0, 100), class = Intercept),
    prior(normal(0, 10), class = b),
    prior(cauchy(0, 2), class = sigma)
  ),
  seed = 8,
  chains = 4,
  iter = 2000,
  cores = 4
)

plot(b8_1_par)
post_8_1 <- posterior_samples(b8_1_par)
pairs(b8_1_par, off_diag_args = list(alpha = 0.1))
brms::waic(b8_1_par)
brms::loo(b8_1_par)
```

# Practice  

## Hard  

#### 8H1  

```{r}
mp <- rethinking::map2stan(
  flist = alist(
    a ~ dnorm(0, 1),
    b ~ dcauchy(0, 1)
  ),
  data = list(y = 1),
  start = list(a = 0, b = 0),
  iter = 1e4, warmup = 100, WAIC = FALSE
)

plot(mp)

# another look at the same sampling:
rnorm(1e4) %>% hist(main = "Standard Normal")
rcauchy(1e4) %>% hist(main = "Standard Cauchy")
```

The cauchy distribution has fat tails, and very large values are possible, though rare.

#### 8H2

```{r}
library(rethinking)
data(WaffleDivorce)

d <- WaffleDivorce

# standardize predictor
d$MedianAgeMarriage.s <- (d$MedianAgeMarriage-mean(d$MedianAgeMarriage))/
  sd(d$MedianAgeMarriage)
d$Marriage.s <- (d$Marriage - mean(d$Marriage))/sd(d$Marriage)

m5.1 <- map(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bA * MedianAgeMarriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bA ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) , data = d )

m5.2 <- map(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bR * Marriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bR ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) , data = d )

m5.3 <- map(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bR*Marriage.s + bA*MedianAgeMarriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bR ~ dnorm( 0 , 1 ) ,
    bA ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) ,
  data = d )

m5.1.mcmc <- map2stan(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bA * MedianAgeMarriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bA ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) , data = d[,c("Divorce","MedianAgeMarriage.s")] , warmup=500, iter = 4000, chains=3, cores = 3)

m5.2.mcmc <- map2stan(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bR * Marriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bR ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) , data = d[,c("Divorce","Marriage.s")] , warmup=500, iter = 4000, chains=3, cores = 3)

m5.3.mcmc <- map2stan(
  alist(
    Divorce ~ dnorm( mu , sigma ) ,
    mu <- a + bR*Marriage.s + bA*MedianAgeMarriage.s ,
    a ~ dnorm( 10 , 10 ) ,
    bR ~ dnorm( 0 , 1 ) ,
    bA ~ dnorm( 0 , 1 ) ,
    sigma ~ dunif( 0 , 10 )
  ) ,
  data = d[,c("Divorce","Marriage.s","MedianAgeMarriage.s")] , warmup=500, iter = 4000, chains=3, cores = 3)

compare(m5.1, m5.2, m5.3, m5.1.mcmc, m5.2.mcmc, m5.3.mcmc)

detach(package:rethinking, unload = TRUE)
```

#### 8H3

```{r}
N <- 100
height <- rnorm(N, 10, 2)
leg_prop <- runif(N, 0.4, 0.5)
leg_left <- leg_prop * height + rnorm(N, 0, 0.02)
leg_right <- leg_prop * height + rnorm(N, 0, 0.02)
leg_data <- tibble(height, leg_left, leg_right)

brms::get_prior(formula = height ~ 1 + leg_left + leg_right, family = gaussian(), data = leg_data)

m5.8s <- brm(
  formula = height ~ 1 + leg_left + leg_right,
  family = gaussian(),
  prior = c(
    prior(normal(10, 100), class = Intercept),
    prior(normal(2, 10), class = b),
    prior(cauchy(0, 1), class = sigma)
  ),
  data = leg_data,
  chains = 4, cores = 4
)

m5.8s2 <- brm(
  formula = height ~ 1 + leg_left + leg_right,
  family = gaussian(),
  prior = c(
    prior(normal(10, 100), class = Intercept),
    prior(normal(2, 10), class = b, coef = "leg_left"),
    prior(normal(2, 10), class = b, coef = "leg_right", lb = 0),
    prior(cauchy(0, 1), class = sigma)
  ),
  data = leg_data,
  chains = 4, cores = 4
)

# https://www.rpubs.com/paulessers/Rethinking_8
```

#### 8H6

```{r}
# generate a simulated globe
p_water <- 0.70

num_tosses <- 1e5
positions <- character(length = num_tosses)
globe = c("land" = 1 - p_water, "water" = p_water)
current <- "land"
for ( i in 1:num_tosses ) {
    # record current position
    positions[i] <- current

    # flip coin to generate proposal
    proposal <- sample(names(globe), size = 1)
    
    # move?
    prob_move <- globe[proposal] / globe[current]
    current <- ifelse( runif(1) < prob_move , proposal , current )
}
ggplot(tibble(position = positions), aes(position)) + 
  geom_bar()

mean(positions == "water")
```

